import { Event, User } from "./types";

export const mockUsers: User[] = [
  {
    id: "1",
    name: "Alex Morgan",
    email: "alex@example.com",
    role: "organizer",
  },
  {
    id: "2",
    name: "Jordan Lee",
    email: "jordan@example.com",
    role: "attendee",
  },
  {
    id: "3",
    name: "Sam Wilson",
    email: "sam@example.com",
    role: "organizer",
  },
];

export const mockEvents: Event[] = [
  {
    id: "1",
    title: "Tech Innovation Summit 2026",
    description:
      "Join industry leaders and innovators for a full-day summit exploring the latest breakthroughs in AI, quantum computing, and sustainable technology. Network with 500+ professionals and gain insights into the future of tech.",
    date: "2026-03-15",
    time: "09:00",
    location: "Grand Convention Center, San Francisco",
    category: "conference",
    capacity: 500,
    registered: 342,
    organizerId: "1",
    organizerName: "Alex Morgan",
    status: "upcoming",
    price: 149,
    tags: ["technology", "AI", "networking"],
  },
  {
    id: "2",
    title: "React Advanced Workshop",
    description:
      "A hands-on workshop covering React Server Components, Suspense patterns, and performance optimization techniques. Bring your laptop and get ready to code along with expert instructors.",
    date: "2026-03-22",
    time: "10:00",
    location: "Dev Hub, Austin",
    category: "workshop",
    capacity: 50,
    registered: 38,
    organizerId: "1",
    organizerName: "Alex Morgan",
    status: "upcoming",
    price: 79,
    tags: ["react", "frontend", "workshop"],
  },
  {
    id: "3",
    title: "Startup Founders Meetup",
    description:
      "Monthly meetup for startup founders to share experiences, challenges, and successes. This month's theme: Scaling Your Team From 10 to 100. Includes pizza and networking time.",
    date: "2026-02-28",
    time: "18:30",
    location: "The Hive Co-working, New York",
    category: "meetup",
    capacity: 80,
    registered: 67,
    organizerId: "3",
    organizerName: "Sam Wilson",
    status: "upcoming",
    price: 0,
    tags: ["startup", "networking", "founders"],
  },
  {
    id: "4",
    title: "UX Design Masterclass",
    description:
      "Learn user-centered design principles from a Google Design Lead. Topics include research methods, prototyping, accessibility, and design systems at scale.",
    date: "2026-04-05",
    time: "09:30",
    location: "Design Studio, Seattle",
    category: "seminar",
    capacity: 120,
    registered: 89,
    organizerId: "3",
    organizerName: "Sam Wilson",
    status: "upcoming",
    price: 99,
    tags: ["design", "UX", "product"],
  },
  {
    id: "5",
    title: "Cloud Architecture Deep Dive",
    description:
      "A comprehensive webinar on modern cloud architecture patterns, microservices, serverless computing, and multi-cloud strategies. Q&A with AWS and Azure certified architects.",
    date: "2026-04-12",
    time: "14:00",
    location: "Online (Zoom)",
    category: "webinar",
    capacity: 1000,
    registered: 456,
    organizerId: "1",
    organizerName: "Alex Morgan",
    status: "upcoming",
    price: 29,
    tags: ["cloud", "architecture", "devops"],
  },
  {
    id: "6",
    title: "Annual Tech Social Night",
    description:
      "Unwind with fellow tech enthusiasts at our annual social gathering. Live music, great food, and the chance to connect with people who share your passion for technology.",
    date: "2026-05-01",
    time: "19:00",
    location: "Skyline Rooftop Bar, Chicago",
    category: "social",
    capacity: 200,
    registered: 124,
    organizerId: "3",
    organizerName: "Sam Wilson",
    status: "upcoming",
    price: 35,
    tags: ["social", "networking", "fun"],
  },
];
